server:
  port: "8019"

database:
  active: "mongodb" # or "mongodb"
  mongodb:
    host: "mongo-main"
    port: "27017"
    # user: "Senbox"
    # password: ""
    name: "department_service_db"

consul:
    host: "consul"
    port: 8500
    
registry:
  host: 192.0.2.68

