# This file should be added to .gitignore in production project.
app:
  name: product-service
  version: 1.0.0
  environment: development
  api:
    rest:
      host: 0.0.0.0
      port: 8003
      setting:
        debug: true
        debugErrorsResponse: true
        ignoreLogUrls: [ "metrics" ]

zap:
  cores:
    console:
      type: stream
      level: info
      encoding: console
      time_encoder: iso8601
    file:
      type: file
      encoding: json
      time_encoder: iso8601
      file:
        path: "/logs"
        max_backups: 7
        max_age: 30
        max_size: 32

mongo:
  uri: "mongodb://senbox:senbox@mongodb:27017/"
  username: senbox
  password: senbox
  db: product-service
  connect_timeout: 30
  max_conn_idle_time: 3
  min_pool_size: 20
  max_pool_size: 300
  collections:
    products: products
    categories: categories
    topics: topics
    product_usage_history: product_usage_history

consul:
  host: consul
  port: 8500
  
registry:
  host: 192.0.2.52

kafka:
  client: product-service
  brokers: ["kafka-1:9093", "kafka-2:9093", "kafka-3:9093"]
  replication_factor: 3
  topics:
    product_created:
      name: product-created
      partitions: 1
      replication_factor: 3
    product_updated:
      name: product-updated
      partitions: 1
      replication_factor: 3
    product_deleted:
      name: product-deleted
      partitions: 1
      replication_factor: 3
    product_picked:
      name: product-picked
      partitions: 1
      replication_factor: 3
  groups:
    product_created: product-created
    product_updated: product-updated
    product_deleted: product-deleted
    product_picked: product-picked
  client_config:
    producer_config:
      metadata_max_age: 60 # seconds
      max_buffered_records: 1_000_000
      producer_batch_max_bytes: 16_000_000
      record_partitioner: 1_000_000
    consumer_config:
      metadata_max_age: 60 # seconds
      fetch_max_bytes: 50_000_000
      fetch_max_partition_bytes: 25_000_000
      fetch_max_wait: 10 # seconds
