server:
  port: "8009"

database:
  active: "mongodb" # or "mongodb"
  mongodb:
    host: "mongo-main"
    port: "27017"
    # user: "Senbox"
    # password: ""
    name: "term_service_db"

  redis_cache:
    ttlSeconds: 0 #config time circle cache
    host: "redis"
    port: "6379"
    password: "senbox"
    db: 10

consul:
    host: "consul"
    port: 8500
    
registry:
  host: 192.0.2.58

